"""
Quote Engine
Generates professional PDF quotations for customers.
Uses fpdf2 - lightweight, no external dependencies.
"""
import os
from datetime import datetime, timedelta
from typing import Dict, Any, Optional
from fpdf import FPDF


class QuotePDF(FPDF):
    """Custom PDF with header and footer."""
    
    def __init__(self, business_name: str):
        super().__init__()
        self.business_name = business_name
    
    def header(self):
        self.set_font("Helvetica", "B", 20)
        self.set_text_color(15, 23, 42)
        self.cell(0, 10, self.business_name, align="L")
        self.ln(6)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(100, 116, 139)
        self.cell(0, 6, "Quotation", align="L")
        self.ln(10)
        # Blue line
        self.set_draw_color(59, 130, 246)
        self.set_line_width(0.8)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(10)
    
    def footer(self):
        self.set_y(-30)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, "Generated by Xythe - Your Private AI Assistant", align="C")


class QuoteEngine:
    """Generates PDF quotations."""
    
    def __init__(self, storage_dir: str = "./data/quotes"):
        self.storage_dir = storage_dir
        os.makedirs(storage_dir, exist_ok=True)
    
    def generate_quote(
        self,
        tenant_id: str,
        customer_name: str,
        customer_phone: str,
        business_name: str,
        items: list,
        valid_days: int = 7,
        notes: Optional[str] = None
    ) -> Dict[str, Any]:
        """Generate a quotation PDF."""
        
        quote_id = f"QT-{datetime.now().strftime('%Y%m%d')}-{os.urandom(2).hex().upper()}"
        
        subtotal = sum(item["quantity"] * item["price"] for item in items)
        sst = subtotal * 0.06
        total = subtotal + sst
        valid_until = datetime.now() + timedelta(days=valid_days)
        
        # Create PDF
        pdf = QuotePDF(business_name)
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=25)
        
        # Quote ID and date
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 6, f"Quote: {quote_id}", align="R")
        pdf.ln(4)
        pdf.cell(0, 6, f"Date: {datetime.now().strftime('%d %B %Y')}", align="R")
        pdf.ln(4)
        pdf.cell(0, 6, f"Valid Until: {valid_until.strftime('%d %B %Y')}", align="R")
        pdf.ln(12)
        
        # Customer info
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 8, "Prepared For:", align="L")
        pdf.ln(8)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 6, customer_name, align="L")
        pdf.ln(6)
        pdf.cell(0, 6, customer_phone, align="L")
        pdf.ln(12)
        
        # Table header
        pdf.set_fill_color(59, 130, 246)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        
        col_w = [10, 80, 20, 35, 35]
        headers = ["#", "Item", "Qty", "Unit Price", "Total"]
        
        for i, (header, width) in enumerate(zip(headers, col_w)):
            pdf.cell(width, 10, header, border=0, fill=True, align="C" if i > 1 else "L")
        pdf.ln()
        
        # Table rows
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(15, 23, 42)
        
        for i, item in enumerate(items, 1):
            item_total = item["quantity"] * item["price"]
            
            if i % 2 == 0:
                pdf.set_fill_color(248, 250, 252)
                fill = True
            else:
                fill = False
            
            pdf.cell(col_w[0], 9, str(i), fill=fill, align="L")
            pdf.cell(col_w[1], 9, item["name"], fill=fill, align="L")
            pdf.cell(col_w[2], 9, str(item["quantity"]), fill=fill, align="C")
            pdf.cell(col_w[3], 9, f"RM {item['price']:,.2f}", fill=fill, align="R")
            pdf.cell(col_w[4], 9, f"RM {item_total:,.2f}", fill=fill, align="R")
            pdf.ln()
        
        pdf.ln(6)
        
        # Totals
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(15, 23, 42)
        
        right_x = pdf.get_x() + sum(col_w) - col_w[4]
        pdf.set_x(right_x)
        pdf.cell(col_w[4], 7, f"Subtotal: RM {subtotal:,.2f}", align="R")
        pdf.ln(7)
        pdf.set_x(right_x)
        pdf.cell(col_w[4], 7, f"SST (6%): RM {sst:,.2f}", align="R")
        pdf.ln(7)
        
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(59, 130, 246)
        pdf.set_x(right_x)
        pdf.cell(col_w[4], 9, f"Total: RM {total:,.2f}", align="R")
        pdf.ln(14)
        
        # Notes
        if notes:
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(15, 23, 42)
            pdf.cell(0, 6, "Notes:", align="L")
            pdf.ln(8)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(71, 85, 105)
            pdf.multi_cell(0, 5, notes)
        
        # Save
        filename = f"{quote_id}.pdf"
        tenant_dir = os.path.join(self.storage_dir, tenant_id)
        os.makedirs(tenant_dir, exist_ok=True)
        pdf_path = os.path.join(tenant_dir, filename)
        pdf.output(pdf_path)
        
        return {
            "quote_id": quote_id,
            "pdf_path": pdf_path,
            "filename": filename,
            "subtotal": round(subtotal, 2),
            "sst": round(sst, 2),
            "total": round(total, 2),
            "valid_until": valid_until.strftime("%d %B %Y"),
        }


def test_quote():
    """Test the quote engine."""
    engine = QuoteEngine()
    
    result = engine.generate_quote(
        tenant_id="test",
        customer_name="Mr. Ahmad",
        customer_phone="+60 12-345 6789",
        business_name="Farah Insurance Agency",
        items=[
            {"name": "AIA A-Plus Medical Plan 200", "quantity": 1, "price": 250.00},
            {"name": "AIA Life Protection Plus", "quantity": 1, "price": 180.00},
        ],
        notes="Coverage starts upon first payment. 30-day waiting period for pre-existing conditions."
    )
    
    print(f"Quote: {result['quote_id']}")
    print(f"Total: RM {result['total']:,.2f}")
    print(f"PDF: {result['pdf_path']}")
    return result