"""
WhatsApp Cloud API Client
Handles sending messages, documents, and marking messages as read.
"""
import httpx
from typing import Optional, Dict, Any
from src.config import settings
from src.utils.logging import logger


class WhatsAppClient:
    """
    Wraps Meta's WhatsApp Cloud API.
    Docs: https://developers.facebook.com/docs/whatsapp/cloud-api
    """

    def __init__(self, access_token: Optional[str] = None):
        self.access_token = access_token or settings.WHATSAPP_ACCESS_TOKEN
        self.api_version = settings.WHATSAPP_API_VERSION
        self.base_url = f"https://graph.facebook.com/{self.api_version}"
        self.client = httpx.AsyncClient(timeout=30.0)

    def _headers(self) -> Dict[str, str]:
        return {
            "Authorization": f"Bearer {self.access_token}",
            "Content-Type": "application/json"
        }

    async def send_text(
        self,
        phone_number_id: str,
        to: str,
        text: str
    ) -> Dict[str, Any]:
        """Send a WhatsApp text message."""
        url = f"{self.base_url}/{phone_number_id}/messages"

        payload = {
            "messaging_product": "whatsapp",
            "recipient_type": "individual",
            "to": to,
            "type": "text",
            "text": {
                "preview_url": False,
                "body": text[:4096]  # WhatsApp limit
            }
        }

        try:
            response = await self.client.post(
                url, json=payload, headers=self._headers()
            )
            response.raise_for_status()
            result = response.json()
            msg_id = result.get("messages", [{}])[0].get("id", "unknown")
            logger.info(f"WhatsApp message sent to {to}: {msg_id}")
            return result
        except httpx.HTTPError as e:
            logger.error(f"WhatsApp send failed: {e}")
            raise

    async def send_document(
        self,
        phone_number_id: str,
        to: str,
        document_url: str,
        filename: str = "document.pdf",
        caption: Optional[str] = None
    ) -> Dict[str, Any]:
        """Send a document (PDF, image) via WhatsApp."""
        url = f"{self.base_url}/{phone_number_id}/messages"

        payload = {
            "messaging_product": "whatsapp",
            "recipient_type": "individual",
            "to": to,
            "type": "document",
            "document": {
                "link": document_url,
                "filename": filename
            }
        }

        if caption:
            payload["document"]["caption"] = caption[:1024]

        try:
            response = await self.client.post(
                url, json=payload, headers=self._headers()
            )
            response.raise_for_status()
            logger.info(f"WhatsApp document sent to {to}: {filename}")
            return response.json()
        except httpx.HTTPError as e:
            logger.error(f"WhatsApp document send failed: {e}")
            raise

    async def send_quotation(
        self,
        phone_number_id: str,
        to: str,
        pdf_url: str,
        quote_ref: str,
        total: str
    ) -> Dict[str, Any]:
        """Send a quotation PDF with formatted caption."""
        caption = (
            f"📄 Quotation {quote_ref}\n"
            f"Total: {total}\n\n"
            f"Generated by Xythe"
        )
        return await self.send_document(
            phone_number_id=phone_number_id,
            to=to,
            document_url=pdf_url,
            filename=f"Quotation_{quote_ref}.pdf",
            caption=caption
        )

    async def mark_as_read(
        self, phone_number_id: str, message_id: str
    ) -> Dict[str, Any]:
        """Mark an incoming message as read (show blue ticks)."""
        url = f"{self.base_url}/{phone_number_id}/messages"

        payload = {
            "messaging_product": "whatsapp",
            "status": "read",
            "message_id": message_id
        }

        try:
            response = await self.client.post(
                url, json=payload, headers=self._headers()
            )
            return response.json()
        except httpx.HTTPError as e:
            logger.error(f"Mark as read failed: {e}")
            return {"error": str(e)}

    async def verify_webhook(
        self, mode: str, token: str, challenge: str
    ) -> Optional[int]:
        """Verify WhatsApp webhook subscription challenge."""
        if mode == "subscribe" and token == settings.WHATSAPP_VERIFY_TOKEN:
            return int(challenge)
        return None

    async def close(self):
        """Close the HTTP client."""
        await self.client.aclose()