"""
Quote Model
Tracks every quotation generated by Xythe.
"""
from sqlalchemy import (
    Column, String, Integer, Float, DateTime, ForeignKey, Text
)
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from src.database.connection import Base


class Quote(Base):
    __tablename__ = "quotes"

    id = Column(String(20), primary_key=True)
    # Format: QT-20260626-0042

    tenant_id = Column(
        String(10), ForeignKey("tenants.id"), nullable=False, index=True
    )

    # Customer
    customer_phone = Column(String(20))
    customer_name = Column(String(200))

    # Status flow: sent → followed_up_1 → followed_up_2 → accepted / rejected / expired
    status = Column(String(20), default="sent")

    # Money
    subtotal = Column(Float)
    sst_amount = Column(Float, default=0.0)
    total = Column(Float)

    # Dates
    valid_until = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    converted_at = Column(DateTime(timezone=True))
    conversion_value = Column(Float)

    # PDF
    pdf_url = Column(String(500))

    # Notes
    notes = Column(Text)

    # Relationship: one quote has many items
    items = relationship(
        "QuoteItem", back_populates="quote",
        cascade="all, delete-orphan"
    )


class QuoteItem(Base):
    __tablename__ = "quote_items"

    id = Column(Integer, primary_key=True, autoincrement=True)
    quote_id = Column(
        String(20), ForeignKey("quotes.id"), nullable=False
    )

    item_code = Column(String(50))
    item_name = Column(String(200))
    quantity = Column(Integer)
    unit_price = Column(Float)
    total_price = Column(Float)

    # Relationship
    quote = relationship("Quote", back_populates="items")